# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AerialMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AerialMobile
pod 'CocoaAsyncSocket'
pod 'AFNetworking'
pod 'ObjectiveSugar'
  target 'AerialMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
